# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec91628e510123c1d458cb68b6493c69ff70796c39f8cc8df21996bfa9d036f891503feeaff29ef999373827d5f826fe8d9f6de57cdaf3af080bb6c63b0a166

test:
  secret_key_base: 02e39c0c00060f495af9db67bf9403b2ce26a191738f4d67d5deff6ea0785e856bd7876fea00afc841c63b85348662e7b5eb03e4d110251f7772cb2c48bb6ce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
